//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.19 at 10:16:28 PM CET 
//


package Model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}appliesSource"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}appliesTemporalCharacteristics"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}appliesAuthority"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}appliesJurisdiction"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}inScope" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="hasCreationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "appliesSource",
    "appliesTemporalCharacteristics",
    "appliesAuthority",
    "appliesJurisdiction",
    "inScope"
})
@XmlRootElement(name = "Context")
public class Context {

    @XmlElement(required = true)
    protected AppliesSource appliesSource;
    @XmlElement(required = true)
    protected AppliesTemporalCharacteristics appliesTemporalCharacteristics;
    @XmlElement(required = true)
    protected AppliesAuthority appliesAuthority;
    @XmlElement(required = true)
    protected AppliesJurisdiction appliesJurisdiction;
    @XmlElement(required = true)
    protected List<InScope> inScope;
    @XmlAttribute(name = "hasCreationDate", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String hasCreationDate;
    @XmlAttribute(name = "key", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String key;

    /**
     * Gets the value of the appliesSource property.
     * 
     * @return
     *     possible object is
     *     {@link AppliesSource }
     *     
     */
    public AppliesSource getAppliesSource() {
        return appliesSource;
    }

    /**
     * Sets the value of the appliesSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppliesSource }
     *     
     */
    public void setAppliesSource(AppliesSource value) {
        this.appliesSource = value;
    }

    /**
     * Gets the value of the appliesTemporalCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link AppliesTemporalCharacteristics }
     *     
     */
    public AppliesTemporalCharacteristics getAppliesTemporalCharacteristics() {
        return appliesTemporalCharacteristics;
    }

    /**
     * Sets the value of the appliesTemporalCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppliesTemporalCharacteristics }
     *     
     */
    public void setAppliesTemporalCharacteristics(AppliesTemporalCharacteristics value) {
        this.appliesTemporalCharacteristics = value;
    }

    /**
     * Gets the value of the appliesAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link AppliesAuthority }
     *     
     */
    public AppliesAuthority getAppliesAuthority() {
        return appliesAuthority;
    }

    /**
     * Sets the value of the appliesAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppliesAuthority }
     *     
     */
    public void setAppliesAuthority(AppliesAuthority value) {
        this.appliesAuthority = value;
    }

    /**
     * Gets the value of the appliesJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link AppliesJurisdiction }
     *     
     */
    public AppliesJurisdiction getAppliesJurisdiction() {
        return appliesJurisdiction;
    }

    /**
     * Sets the value of the appliesJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppliesJurisdiction }
     *     
     */
    public void setAppliesJurisdiction(AppliesJurisdiction value) {
        this.appliesJurisdiction = value;
    }

    /**
     * Gets the value of the inScope property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inScope property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInScope().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InScope }
     * 
     * 
     */
    public List<InScope> getInScope() {
        if (inScope == null) {
            inScope = new ArrayList<InScope>();
        }
        return this.inScope;
    }

    /**
     * Gets the value of the hasCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasCreationDate() {
        return hasCreationDate;
    }

    /**
     * Sets the value of the hasCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasCreationDate(String value) {
        this.hasCreationDate = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

}
