//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.19 at 10:16:28 PM CET 
//


package Model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}Comment"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}LegalSources"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}Times"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}TemporalCharacteristics"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}Authorities"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}Jurisdictions"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}Associations"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}Context"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}Statements" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "comment",
    "legalSources",
    "times",
    "temporalCharacteristics",
    "authorities",
    "jurisdictions",
    "associations",
    "context",
    "statements"
})
@XmlRootElement(name = "LegalRuleML")
public class LegalRuleML {

    @XmlElement(name = "Comment", required = true)
    protected String comment;
    @XmlElement(name = "LegalSources", required = true)
    protected LegalSources legalSources;
    @XmlElement(name = "Times", required = true)
    protected Times times;
    @XmlElement(name = "TemporalCharacteristics", required = true)
    protected TemporalCharacteristics temporalCharacteristics;
    @XmlElement(name = "Authorities", required = true)
    protected Authorities authorities;
    @XmlElement(name = "Jurisdictions", required = true)
    protected Jurisdictions jurisdictions;
    @XmlElement(name = "Associations", required = true)
    protected Associations associations;
    @XmlElement(name = "Context", required = true)
    protected Context context;
    @XmlElement(name = "Statements", required = true)
    protected List<Statements> statements;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the legalSources property.
     * 
     * @return
     *     possible object is
     *     {@link LegalSources }
     *     
     */
    public LegalSources getLegalSources() {
        return legalSources;
    }

    /**
     * Sets the value of the legalSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalSources }
     *     
     */
    public void setLegalSources(LegalSources value) {
        this.legalSources = value;
    }

    /**
     * Gets the value of the times property.
     * 
     * @return
     *     possible object is
     *     {@link Times }
     *     
     */
    public Times getTimes() {
        return times;
    }

    /**
     * Sets the value of the times property.
     * 
     * @param value
     *     allowed object is
     *     {@link Times }
     *     
     */
    public void setTimes(Times value) {
        this.times = value;
    }

    /**
     * Gets the value of the temporalCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalCharacteristics }
     *     
     */
    public TemporalCharacteristics getTemporalCharacteristics() {
        return temporalCharacteristics;
    }

    /**
     * Sets the value of the temporalCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalCharacteristics }
     *     
     */
    public void setTemporalCharacteristics(TemporalCharacteristics value) {
        this.temporalCharacteristics = value;
    }

    /**
     * Gets the value of the authorities property.
     * 
     * @return
     *     possible object is
     *     {@link Authorities }
     *     
     */
    public Authorities getAuthorities() {
        return authorities;
    }

    /**
     * Sets the value of the authorities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authorities }
     *     
     */
    public void setAuthorities(Authorities value) {
        this.authorities = value;
    }

    /**
     * Gets the value of the jurisdictions property.
     * 
     * @return
     *     possible object is
     *     {@link Jurisdictions }
     *     
     */
    public Jurisdictions getJurisdictions() {
        return jurisdictions;
    }

    /**
     * Sets the value of the jurisdictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Jurisdictions }
     *     
     */
    public void setJurisdictions(Jurisdictions value) {
        this.jurisdictions = value;
    }

    /**
     * Gets the value of the associations property.
     * 
     * @return
     *     possible object is
     *     {@link Associations }
     *     
     */
    public Associations getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Associations }
     *     
     */
    public void setAssociations(Associations value) {
        this.associations = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link Context }
     *     
     */
    public Context getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link Context }
     *     
     */
    public void setContext(Context value) {
        this.context = value;
    }

    /**
     * Gets the value of the statements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Statements }
     * 
     * 
     */
    public List<Statements> getStatements() {
        if (statements == null) {
            statements = new ArrayList<Statements>();
        }
        return this.statements;
    }

	public String toString() {
		return "LegalRuleML [comment=" + comment + ", legalSources=" + legalSources + ", times=" + times
				+ ", temporalCharacteristics=" + temporalCharacteristics + ", authorities=" + authorities
				+ ", jurisdictions=" + jurisdictions + ", associations=" + associations + ", context=" + context
				+ ", statements=" + statements + "]";
	}

}
