//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.19 at 10:16:28 PM CET 
//


package Model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the TRANG package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Var_QNAME = new QName("http://ruleml.org/spec", "Var");
    private final static QName _Comment_QNAME = new QName("http://docs.oasis-open.org/legalruleml/ns/v1.0/", "Comment");
    private final static QName _Ind_QNAME = new QName("http://ruleml.org/spec", "Ind");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: TRANG
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AppliesPenalty }
     * 
     */
    public AppliesPenalty createAppliesPenalty() {
        return new AppliesPenalty();
    }

    /**
     * Create an instance of {@link ForStatus }
     * 
     */
    public ForStatus createForStatus() {
        return new ForStatus();
    }

    /**
     * Create an instance of {@link Obligation }
     * 
     */
    public Obligation createObligation() {
        return new Obligation();
    }

    /**
     * Create an instance of {@link And }
     * 
     */
    public And createAnd() {
        return new And();
    }

    /**
     * Create an instance of {@link Atom }
     * 
     */
    public Atom createAtom() {
        return new Atom();
    }

    /**
     * Create an instance of {@link Rel }
     * 
     */
    public Rel createRel() {
        return new Rel();
    }

    /**
     * Create an instance of {@link Or }
     * 
     */
    public Or createOr() {
        return new Or();
    }

    /**
     * Create an instance of {@link AppliesTemporalCharacteristics }
     * 
     */
    public AppliesTemporalCharacteristics createAppliesTemporalCharacteristics() {
        return new AppliesTemporalCharacteristics();
    }

    /**
     * Create an instance of {@link AppliesJurisdiction }
     * 
     */
    public AppliesJurisdiction createAppliesJurisdiction() {
        return new AppliesJurisdiction();
    }

    /**
     * Create an instance of {@link Authority }
     * 
     */
    public Authority createAuthority() {
        return new Authority();
    }

    /**
     * Create an instance of {@link OverrideStatement }
     * 
     */
    public OverrideStatement createOverrideStatement() {
        return new OverrideStatement();
    }

    /**
     * Create an instance of {@link Override }
     * 
     */
    public Override createOverride() {
        return new Override();
    }

    /**
     * Create an instance of {@link InScope }
     * 
     */
    public InScope createInScope() {
        return new InScope();
    }

    /**
     * Create an instance of {@link PenaltyStatement }
     * 
     */
    public PenaltyStatement createPenaltyStatement() {
        return new PenaltyStatement();
    }

    /**
     * Create an instance of {@link SuborderList }
     * 
     */
    public SuborderList createSuborderList() {
        return new SuborderList();
    }

    /**
     * Create an instance of {@link Prohibition }
     * 
     */
    public Prohibition createProhibition() {
        return new Prohibition();
    }

    /**
     * Create an instance of {@link PrescriptiveStatement }
     * 
     */
    public PrescriptiveStatement createPrescriptiveStatement() {
        return new PrescriptiveStatement();
    }

    /**
     * Create an instance of {@link Rule }
     * 
     */
    public Rule createRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link HasStrength }
     * 
     */
    public HasStrength createHasStrength() {
        return new HasStrength();
    }

    /**
     * Create an instance of {@link Defeater }
     * 
     */
    public Defeater createDefeater() {
        return new Defeater();
    }

    /**
     * Create an instance of {@link If }
     * 
     */
    public If createIf() {
        return new If();
    }

    /**
     * Create an instance of {@link Then }
     * 
     */
    public Then createThen() {
        return new Then();
    }

    /**
     * Create an instance of {@link Permission }
     * 
     */
    public Permission createPermission() {
        return new Permission();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link AppliesAuthority }
     * 
     */
    public AppliesAuthority createAppliesAuthority() {
        return new AppliesAuthority();
    }

    /**
     * Create an instance of {@link AppliesSource }
     * 
     */
    public AppliesSource createAppliesSource() {
        return new AppliesSource();
    }

    /**
     * Create an instance of {@link ToTarget }
     * 
     */
    public ToTarget createToTarget() {
        return new ToTarget();
    }

    /**
     * Create an instance of {@link LegalSource }
     * 
     */
    public LegalSource createLegalSource() {
        return new LegalSource();
    }

    /**
     * Create an instance of {@link Reparation }
     * 
     */
    public Reparation createReparation() {
        return new Reparation();
    }

    /**
     * Create an instance of {@link ToPrescriptiveStatement }
     * 
     */
    public ToPrescriptiveStatement createToPrescriptiveStatement() {
        return new ToPrescriptiveStatement();
    }

    /**
     * Create an instance of {@link Jurisdictions }
     * 
     */
    public Jurisdictions createJurisdictions() {
        return new Jurisdictions();
    }

    /**
     * Create an instance of {@link Jurisdiction }
     * 
     */
    public Jurisdiction createJurisdiction() {
        return new Jurisdiction();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link Associations }
     * 
     */
    public Associations createAssociations() {
        return new Associations();
    }

    /**
     * Create an instance of {@link AtTime }
     * 
     */
    public AtTime createAtTime() {
        return new AtTime();
    }

    /**
     * Create an instance of {@link TemporalCharacteristics }
     * 
     */
    public TemporalCharacteristics createTemporalCharacteristics() {
        return new TemporalCharacteristics();
    }

    /**
     * Create an instance of {@link TemporalCharacteristic }
     * 
     */
    public TemporalCharacteristic createTemporalCharacteristic() {
        return new TemporalCharacteristic();
    }

    /**
     * Create an instance of {@link HasStatusDevelopment }
     * 
     */
    public HasStatusDevelopment createHasStatusDevelopment() {
        return new HasStatusDevelopment();
    }

    /**
     * Create an instance of {@link Times }
     * 
     */
    public Times createTimes() {
        return new Times();
    }

    /**
     * Create an instance of {@link Time }
     * 
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link LegalSources }
     * 
     */
    public LegalSources createLegalSources() {
        return new LegalSources();
    }

    /**
     * Create an instance of {@link Authorities }
     * 
     */
    public Authorities createAuthorities() {
        return new Authorities();
    }

    /**
     * Create an instance of {@link Statements }
     * 
     */
    public Statements createStatements() {
        return new Statements();
    }

    /**
     * Create an instance of {@link ReparationStatement }
     * 
     */
    public ReparationStatement createReparationStatement() {
        return new ReparationStatement();
    }

    /**
     * Create an instance of {@link LegalRuleML }
     * 
     */
    public LegalRuleML createLegalRuleML() {
        return new LegalRuleML();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ruleml.org/spec", name = "Var")
    public JAXBElement<String> createVar(String value) {
        return new JAXBElement<String>(_Var_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/legalruleml/ns/v1.0/", name = "Comment")
    public JAXBElement<String> createComment(String value) {
        return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ruleml.org/spec", name = "Ind")
    public JAXBElement<String> createInd(String value) {
        return new JAXBElement<String>(_Ind_QNAME, String.class, null, value);
    }

}
