//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.19 at 10:16:28 PM CET 
//


package Model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}appliesPenalty"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}toPrescriptiveStatement"/>
 *       &lt;/sequence>
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "appliesPenalty",
    "toPrescriptiveStatement"
})
@XmlRootElement(name = "Reparation")
public class Reparation {

    @XmlElement(required = true)
    protected AppliesPenalty appliesPenalty;
    @XmlElement(required = true)
    protected ToPrescriptiveStatement toPrescriptiveStatement;
    @XmlAttribute(name = "key", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String key;

    /**
     * Gets the value of the appliesPenalty property.
     * 
     * @return
     *     possible object is
     *     {@link AppliesPenalty }
     *     
     */
    public AppliesPenalty getAppliesPenalty() {
        return appliesPenalty;
    }

    /**
     * Sets the value of the appliesPenalty property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppliesPenalty }
     *     
     */
    public void setAppliesPenalty(AppliesPenalty value) {
        this.appliesPenalty = value;
    }

    /**
     * Gets the value of the toPrescriptiveStatement property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrescriptiveStatement }
     *     
     */
    public ToPrescriptiveStatement getToPrescriptiveStatement() {
        return toPrescriptiveStatement;
    }

    /**
     * Sets the value of the toPrescriptiveStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrescriptiveStatement }
     *     
     */
    public void setToPrescriptiveStatement(ToPrescriptiveStatement value) {
        this.toPrescriptiveStatement = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

}
