//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.19 at 10:16:28 PM CET 
//


package Model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}hasStrength"/>
 *         &lt;element ref="{http://ruleml.org/spec}if"/>
 *         &lt;element ref="{http://ruleml.org/spec}then"/>
 *       &lt;/sequence>
 *       &lt;attribute name="keyref" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hasStrength",
    "_if",
    "then"
})
@XmlRootElement(name = "Rule", namespace = "http://ruleml.org/spec")
public class Rule {

    @XmlElement(required = true)
    protected HasStrength hasStrength;
    @XmlElement(name = "if", namespace = "http://ruleml.org/spec", required = true)
    protected If _if;
    @XmlElement(namespace = "http://ruleml.org/spec", required = true)
    protected Then then;
    @XmlAttribute(name = "keyref", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String keyref;
    @XmlAttribute(name = "key", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String key;

    /**
     * Gets the value of the hasStrength property.
     * 
     * @return
     *     possible object is
     *     {@link HasStrength }
     *     
     */
    public HasStrength getHasStrength() {
        return hasStrength;
    }

    /**
     * Sets the value of the hasStrength property.
     * 
     * @param value
     *     allowed object is
     *     {@link HasStrength }
     *     
     */
    public void setHasStrength(HasStrength value) {
        this.hasStrength = value;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link If }
     *     
     */
    public If getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link If }
     *     
     */
    public void setIf(If value) {
        this._if = value;
    }

    /**
     * Gets the value of the then property.
     * 
     * @return
     *     possible object is
     *     {@link Then }
     *     
     */
    public Then getThen() {
        return then;
    }

    /**
     * Sets the value of the then property.
     * 
     * @param value
     *     allowed object is
     *     {@link Then }
     *     
     */
    public void setThen(Then value) {
        this.then = value;
    }

    /**
     * Gets the value of the keyref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyref() {
        return keyref;
    }

    /**
     * Sets the value of the keyref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyref(String value) {
        this.keyref = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

}
