//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.19 at 10:16:28 PM CET 
//


package Model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}PrescriptiveStatement"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}PenaltyStatement"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}ReparationStatement" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}OverrideStatement"/>
 *       &lt;/choice>
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prescriptiveStatement",
    "penaltyStatement",
    "reparationStatement",
    "overrideStatement"
})
@XmlRootElement(name = "Statements")
public class Statements {

    @XmlElement(name = "PrescriptiveStatement")
    protected PrescriptiveStatement prescriptiveStatement;
    @XmlElement(name = "PenaltyStatement")
    protected PenaltyStatement penaltyStatement;
    @XmlElement(name = "ReparationStatement")
    protected List<ReparationStatement> reparationStatement;
    @XmlElement(name = "OverrideStatement")
    protected OverrideStatement overrideStatement;
    @XmlAttribute(name = "key")
    @XmlSchemaType(name = "anySimpleType")
    protected String key;

    /**
     * Gets the value of the prescriptiveStatement property.
     * 
     * @return
     *     possible object is
     *     {@link PrescriptiveStatement }
     *     
     */
    public PrescriptiveStatement getPrescriptiveStatement() {
        return prescriptiveStatement;
    }

    /**
     * Sets the value of the prescriptiveStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrescriptiveStatement }
     *     
     */
    public void setPrescriptiveStatement(PrescriptiveStatement value) {
        this.prescriptiveStatement = value;
    }

    /**
     * Gets the value of the penaltyStatement property.
     * 
     * @return
     *     possible object is
     *     {@link PenaltyStatement }
     *     
     */
    public PenaltyStatement getPenaltyStatement() {
        return penaltyStatement;
    }

    /**
     * Sets the value of the penaltyStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link PenaltyStatement }
     *     
     */
    public void setPenaltyStatement(PenaltyStatement value) {
        this.penaltyStatement = value;
    }

    /**
     * Gets the value of the reparationStatement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reparationStatement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReparationStatement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReparationStatement }
     * 
     * 
     */
    public List<ReparationStatement> getReparationStatement() {
        if (reparationStatement == null) {
            reparationStatement = new ArrayList<ReparationStatement>();
        }
        return this.reparationStatement;
    }

    /**
     * Gets the value of the overrideStatement property.
     * 
     * @return
     *     possible object is
     *     {@link OverrideStatement }
     *     
     */
    public OverrideStatement getOverrideStatement() {
        return overrideStatement;
    }

    /**
     * Sets the value of the overrideStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverrideStatement }
     *     
     */
    public void setOverrideStatement(OverrideStatement value) {
        this.overrideStatement = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

	public String toString() {
		return "Statements [prescriptiveStatement=" + prescriptiveStatement + ", penaltyStatement=" + penaltyStatement
				+ ", reparationStatement=" + reparationStatement + ", overrideStatement=" + overrideStatement + ", key="
				+ key + "]";
	}

}
