//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.19 at 10:16:28 PM CET 
//


package Model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}forStatus"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}hasStatusDevelopment"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legalruleml/ns/v1.0/}atTime"/>
 *       &lt;/sequence>
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "forStatus",
    "hasStatusDevelopment",
    "atTime"
})
@XmlRootElement(name = "TemporalCharacteristic")
public class TemporalCharacteristic {

    @XmlElement(required = true)
    protected ForStatus forStatus;
    @XmlElement(required = true)
    protected HasStatusDevelopment hasStatusDevelopment;
    @XmlElement(required = true)
    protected AtTime atTime;
    @XmlAttribute(name = "key", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String key;

    /**
     * Gets the value of the forStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ForStatus }
     *     
     */
    public ForStatus getForStatus() {
        return forStatus;
    }

    /**
     * Sets the value of the forStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForStatus }
     *     
     */
    public void setForStatus(ForStatus value) {
        this.forStatus = value;
    }

    /**
     * Gets the value of the hasStatusDevelopment property.
     * 
     * @return
     *     possible object is
     *     {@link HasStatusDevelopment }
     *     
     */
    public HasStatusDevelopment getHasStatusDevelopment() {
        return hasStatusDevelopment;
    }

    /**
     * Sets the value of the hasStatusDevelopment property.
     * 
     * @param value
     *     allowed object is
     *     {@link HasStatusDevelopment }
     *     
     */
    public void setHasStatusDevelopment(HasStatusDevelopment value) {
        this.hasStatusDevelopment = value;
    }

    /**
     * Gets the value of the atTime property.
     * 
     * @return
     *     possible object is
     *     {@link AtTime }
     *     
     */
    public AtTime getAtTime() {
        return atTime;
    }

    /**
     * Sets the value of the atTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtTime }
     *     
     */
    public void setAtTime(AtTime value) {
        this.atTime = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

}
